### PR TITLE
Draft state after submit for review - FIXED

### PR DESCRIPTION
**Pull request by ferPrieto**
There was a missing step. After submitting the app for review, the response should have been checked.
In case the response had the below parameters:
*CODE: **204144660**
*MSG contained **It may take 2-5 minutes**
The 'submit for review' call had to be attempted again after 2-5 mins, and show the result right after. This is how the AppGalleryConnect API works.

### CODE REVIEW

**Comment by arnekaiser** [comment]
Thank you @ferPrieto for your contribution! 

We should only check the error code and not the content of the message, that's a bad practice and will probably fail soon.

"If your app package is not an AAB package, wait for a while after receiving the error code 204144660 and submit an app release application again."

**Comment by ferPrieto** [comment]
No that's not correct, because in AppGallery Connect there are a couple of more error messages (about a different submission issues) with the same error code. 
For example, if the package name is missing, the error code retrieved is 204144660. The same way when the version name is wrong or missing.

Hope that helps to better understanding that condition

**Comment by arnekaiser** [comment]
OMG, why don't they use a different or a second error code for that?

Is there any documentation of the different messages?

**Comment by ferPrieto** [comment]
I thought the same, the first time too. I spoke with my colleagues from Huawei HQ and there was no other way to detect this specific case (when the app is still being built in the server).

I suggest you to check the next two links:
https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-returncode_v2
https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-release_app

But none of them speak about the different errors with the same code ** 204144660** 

By the way, the fix I did yesterday was tested with some of my apps in production and it worked. 👍

**Comment by arnekaiser** [comment]
This will work until the message is different. We will see ... ;)

Ok, I will merge this pull request, add a note and release a new version. Thank you!

**Pull request merged**
